# GET http://localhost:3000/palestrantes
# Content-Type: application/json


GET http://localhost:3000/palestras
Content-Type: application/json


# GET http://localhost:3000/inscritos
# Content-Type: application/json
