GET http://localhost:3000/palestrantes/5efe083a22eb6f023478966e
Content-Type: application/json


//GET http://localhost:3000/palestras/5f034790f43a4258a816392b
//Content-Type: application/json


//GET http://localhost:3000/inscritos/5f034790f43a4258a816392b
//Content-Type: application/json
